sudo: required
language: go
go:
  - "1.13"
services:
  - docker
jobs:
  include:
    # dont push to dockerhub on forks
    # TODO: restore integration tests on Travis once the story around pushing flyteadmin images to dockerhub is resolved
    - if: fork = true
      stage: test
      name: build test
      install: true
      script: BUILD_PHASE=builder make docker_build
    - if: fork = false
      stage: test
      name: build
      install: true
      script: BUILD_PHASE=builder make docker_build
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
    - stage: test
      install: make install
      name: lint
      script: make lint
