sudo: required
language: go
go:
  - "1.13"
services:
  - docker
jobs:
  include:
    # dont push to dockerhub on forks
    - if: fork = true
      stage: test
      name: build test
      install: true
      script: BUILD_PHASE=builder make docker_build && make k8s_integration
    - if: fork = false
      stage: test
      name: build, integration test, and push
      install: true
      script: BUILD_PHASE=builder make docker_build && make k8s_integration
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
    - stage: test
      install: make install
      name: lint
      script: make lint
