name: Flyteadmin Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - debug-test

jobs:
  docker-build:
    name: Docker Build Images
    uses: flyteorg/flytetools/.github/workflows/docker_build.yml@master

  endtoend:
    name: End2End Test
    needs: [docker-build]
    uses: flyteorg/flytetools/.github/workflows/end2end.yml@releases-end2end
    with:
      priorities: "P0"
      cache_key: ${{ needs.docker-build.outputs.cache_key }}
